name: Validate and Release

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  push:
    branches:
      - "main"
    tags:
      - "*"
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  validate_and_release:
    name: Validate and release build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure CHANGELOG is updated
        uses: dangoslen/changelog-enforcer@v3
      - name: Run tests
        run: make test
      - name: Install tfenv
        shell: bash
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
      - name: Run integration test
        run: make integration-test
      - name: Run GoReleaser (release mode)
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
      - name: Run GoReleaser (build mode)
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot
        if: startsWith(github.ref, 'refs/tags/') == false